/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuestSignupRouteImport } from './routes/_guest/signup'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as AuthAppRouteRouteImport } from './routes/_auth/app/route'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAiSpeechRouteImport } from './routes/api/ai/speech'
import { Route as ApiAiChatRouteImport } from './routes/api/ai/chat'
import { Route as AuthAppChatRouteRouteImport } from './routes/_auth/app/chat/route'
import { Route as AuthAppReaderIndexRouteImport } from './routes/_auth/app/reader/index'
import { Route as AuthAppChatChar123ChatIdChar125RouteImport } from './routes/_auth/app/chat/{-$chatId}'

const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const AuthAppRouteRoute = AuthAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSpeechRoute = ApiAiSpeechRouteImport.update({
  id: '/api/ai/speech',
  path: '/api/ai/speech',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppChatRouteRoute = AuthAppChatRouteRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppReaderIndexRoute = AuthAppReaderIndexRouteImport.update({
  id: '/reader/',
  path: '/reader/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppChatChar123ChatIdChar125Route =
  AuthAppChatChar123ChatIdChar125RouteImport.update({
    id: '/{-$chatId}',
    path: '/{-$chatId}',
    getParentRoute: () => AuthAppChatRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AuthAppRouteRouteWithChildren
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/app/chat': typeof AuthAppChatRouteRouteWithChildren
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/speech': typeof ApiAiSpeechRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/': typeof AuthAppIndexRoute
  '/app/chat/{-$chatId}': typeof AuthAppChatChar123ChatIdChar125Route
  '/app/reader/': typeof AuthAppReaderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/app/chat': typeof AuthAppChatRouteRouteWithChildren
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/speech': typeof ApiAiSpeechRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app': typeof AuthAppIndexRoute
  '/app/chat/{-$chatId}': typeof AuthAppChatChar123ChatIdChar125Route
  '/app/reader': typeof AuthAppReaderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/_auth/app': typeof AuthAppRouteRouteWithChildren
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/_auth/app/chat': typeof AuthAppChatRouteRouteWithChildren
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/speech': typeof ApiAiSpeechRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/app/': typeof AuthAppIndexRoute
  '/_auth/app/chat/{-$chatId}': typeof AuthAppChatChar123ChatIdChar125Route
  '/_auth/app/reader/': typeof AuthAppReaderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/chat'
    | '/api/ai/chat'
    | '/api/ai/speech'
    | '/api/auth/$'
    | '/app/'
    | '/app/chat/{-$chatId}'
    | '/app/reader/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app/chat'
    | '/api/ai/chat'
    | '/api/ai/speech'
    | '/api/auth/$'
    | '/app'
    | '/app/chat/{-$chatId}'
    | '/app/reader'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_guest'
    | '/_auth/app'
    | '/_guest/login'
    | '/_guest/signup'
    | '/_auth/app/chat'
    | '/api/ai/chat'
    | '/api/ai/speech'
    | '/api/auth/$'
    | '/_auth/app/'
    | '/_auth/app/chat/{-$chatId}'
    | '/_auth/app/reader/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiAiSpeechRoute: typeof ApiAiSpeechRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_auth/app': {
      id: '/_auth/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/speech': {
      id: '/api/ai/speech'
      path: '/api/ai/speech'
      fullPath: '/api/ai/speech'
      preLoaderRoute: typeof ApiAiSpeechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/chat': {
      id: '/_auth/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AuthAppChatRouteRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/reader/': {
      id: '/_auth/app/reader/'
      path: '/reader'
      fullPath: '/app/reader/'
      preLoaderRoute: typeof AuthAppReaderIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/chat/{-$chatId}': {
      id: '/_auth/app/chat/{-$chatId}'
      path: '/{-$chatId}'
      fullPath: '/app/chat/{-$chatId}'
      preLoaderRoute: typeof AuthAppChatChar123ChatIdChar125RouteImport
      parentRoute: typeof AuthAppChatRouteRoute
    }
  }
}

interface AuthAppChatRouteRouteChildren {
  AuthAppChatChar123ChatIdChar125Route: typeof AuthAppChatChar123ChatIdChar125Route
}

const AuthAppChatRouteRouteChildren: AuthAppChatRouteRouteChildren = {
  AuthAppChatChar123ChatIdChar125Route: AuthAppChatChar123ChatIdChar125Route,
}

const AuthAppChatRouteRouteWithChildren =
  AuthAppChatRouteRoute._addFileChildren(AuthAppChatRouteRouteChildren)

interface AuthAppRouteRouteChildren {
  AuthAppChatRouteRoute: typeof AuthAppChatRouteRouteWithChildren
  AuthAppIndexRoute: typeof AuthAppIndexRoute
  AuthAppReaderIndexRoute: typeof AuthAppReaderIndexRoute
}

const AuthAppRouteRouteChildren: AuthAppRouteRouteChildren = {
  AuthAppChatRouteRoute: AuthAppChatRouteRouteWithChildren,
  AuthAppIndexRoute: AuthAppIndexRoute,
  AuthAppReaderIndexRoute: AuthAppReaderIndexRoute,
}

const AuthAppRouteRouteWithChildren = AuthAppRouteRoute._addFileChildren(
  AuthAppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthAppRouteRoute: typeof AuthAppRouteRouteWithChildren
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAppRouteRoute: AuthAppRouteRouteWithChildren,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestSignupRoute: typeof GuestSignupRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestSignupRoute: GuestSignupRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiAiSpeechRoute: ApiAiSpeechRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
